const content=document.getElementById('content');
const overlay=document.getElementById('overlay');
let lastFocus=null;
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3400)}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出 '+name)}
function config(){return{prototype:true,description:'仅设计演示，不是实际计算结果',created_at:new Date().toISOString(),factors:[...State.selectedFactors],dataset:State.dataset,model:State.model,strategy:State.strategy,backtest:State.backtest||{},versions:{feature_set:State.featureSetSaved?'FS-DRAFT-009':'FS-008-DEMO',dataset:State.dataset.version||'ds_research_v003'}}}
function modal(title,body,buttons='',drawer=false){lastFocus=document.activeElement;overlay.innerHTML=`<section class="modal ${drawer?'drawer':''}" role="dialog" aria-modal="true" aria-label="${escapeHTML(title)}"><div class="modal-head"><h2>${title}</h2><button class="modal-close" data-action="close-modal" aria-label="关闭">×</button></div><div class="modal-body">${body}</div>${buttons?`<div class="modal-footer">${buttons}</div>`:''}</section>`;overlay.hidden=false;document.body.style.overflow='hidden';overlay.querySelector('button,input,select')?.focus()}
function closeModal(){overlay.hidden=true;overlay.innerHTML='';document.body.style.overflow='';lastFocus?.focus()}
function render(keepScroll=false){const scroll=window.scrollY;const page=navItems.find(x=>x[0]===State.page)||navItems[0];document.title=`${page[2]} · 研序 QUANT 系统设计`;document.getElementById('sidebar').innerHTML=`<div class="brand"><div class="brand-mark">∿</div><div><div class="brand-name">研序 <small style="font-size:10px;letter-spacing:1px">QUANT</small></div><div class="brand-sub">RESEARCH WORKSPACE</div></div></div><button class="nav-item ${State.page==='overview'?'active':''}" data-page="overview"><span class="nav-icon">◫</span>研究工作台</button><div class="nav-section">RESEARCH &nbsp; / &nbsp; 研究链路</div>${navItems.filter(x=>['data','compute','factors','selection','dataset','training','strategy','backtest'].includes(x[0])).map(x=>`<button class="nav-item ${State.page===x[0]?'active':''}" data-page="${x[0]}"><span class="nav-icon">${x[1]}</span>${x[2]}${x[0]==='factors'?'<span class="nav-count">16</span>':''}</button>`).join('')}<button class="nav-item ${State.page==='intelligence'?'active':''}" data-page="intelligence"><span class="nav-icon">⌁</span>情报研究</button><div class="nav-section">OPERATIONS &nbsp; / &nbsp; 管理</div>${navItems.filter(x=>['monitor','tasks','blueprint'].includes(x[0])).map(x=>`<button class="nav-item ${State.page===x[0]?'active':''}" data-page="${x[0]}"><span class="nav-icon">${x[1]}</span>${x[2]}</button>`).join('')}<div class="sidebar-bottom"><span style="color:#82b69e">●</span> &nbsp; 设计演示工作区<br><span style="font-size:10px">本地原型 · 尚未接入数据服务</span></div>`;
 document.getElementById('topbar').innerHTML=`<div class="toolbar"><button class="btn menu-toggle" data-action="toggle-nav" aria-label="展开菜单">☰</button><span class="crumb">研究空间 &nbsp; / &nbsp; <strong>${page[2]}</strong></span></div><div class="top-actions"><button class="search-trigger" data-action="search">⌕ &nbsp; 搜索页面与研究资产 <kbd>Ctrl K</kbd></button>${UI.badge('设计原型 · 演示数据','amber')}<span class="avatar">Q</span></div>`;
 document.getElementById('page-heading').innerHTML=`<div><div class="page-meta">${State.page==='overview'?'WORKSPACE / 01':'QUANT RESEARCH / '+String(navItems.indexOf(page)+1).padStart(2,'0')}</div><h1>${page[2]}</h1><p>${page[3]}</p></div><div class="toolbar"><button class="btn" data-page="blueprint">◇ &nbsp; 系统设计说明</button><button class="btn btn-primary" data-action="${State.page==='overview'?'new-research':'export-config'}">${State.page==='overview'?'+ 新建研究':'↓ 导出配置'}</button></div>`;
 try{content.innerHTML=Pages[State.page]?Pages[State.page]():`<div class="card"><div class="card-head"><h2>设计模块正在补齐</h2></div><div class="card-body"><p class="muted">请先浏览已完成的研究页面。</p><button class="btn" data-page="overview">返回工作台</button></div></div>`}catch(e){content.innerHTML=`<div class="notice notice-amber">页面加载异常：${escapeHTML(e.message)}</div>`;console.error(e)}
 content.classList.remove('page-enter');void content.offsetWidth;content.classList.add('page-enter');if(keepScroll)window.scrollTo(0,scroll);else window.scrollTo(0,0);}
function navigate(page,tab){if(page==='jobs')page='tasks';if(!navItems.some(x=>x[0]===page))return;State.page=page;if(page==='data'&&tab)State.dataTab=tab;history.replaceState(null,'','#'+page);document.body.classList.remove('nav-open');render()}
function invalidate(scope){if(scope==='factors'||scope==='dataset'){State.datasetSaved=false;State.experimentCreated=false;State.modelRegistered=false;}if(scope!=='backtest'){State.strategySaved=false;State.backtestCreated=false;}}
function pushTask(name,type,status='演示完成'){const t={id:'LOCAL-'+String(State.tasks.length+1).padStart(3,'0'),name,type,status,progress:status.includes('完成')?100:0};State.tasks.unshift(t);return t}
function factorDetail(id){const f=FACTORS.find(x=>x.id===id);if(!f)return;modal(`${f.name} · ${f.version}`,`<div class="toolbar">${UI.badge(f.category,'blue')}${UI.badge(f.role,'green')}${UI.badge(f.status,f.status==='已完成'?'green':'amber')}</div><p style="margin:17px 0;color:#82949b">${f.description}</p><pre class="code">${escapeHTML(f.formula)}</pre><div class="grid-3" style="margin:18px 0">${UI.metric('原始 Rank IC',f.ic??'—','演示训练窗口')}${UI.metric('原始 ICIR',f.ir??'—','非年化，保留符号')}${UI.metric('覆盖率',f.coverage+'%','示例研究股票池')}</div>${UI.card('因子画像与研究证据','所有指标绑定版本、股票池与标签',UI.table(['维度','说明'],[['用途',f.role],['研究方向',f.direction+' · 仅在训练集确定'],['标签','t+1 开盘 → t+6 开盘收益'],['评估窗口','2021—2023 训练区间 · 演示'],['下游引用','FS-008 → ds_research_v003 → EXP-024'],['质量门槛','计算完成，覆盖率 ≥ 98%；有效性另行验证']]))}<div class="divider"></div>${UI.lineChart({series:[{name:'月度 Rank IC · 画像示例',color:'#349776',values:[.028,.047,.031,-.005,.041,.06,.025,.039,.052,.029,.047,.036].map(x=>f.ic<0?-x:x)}],labels:['01月','03月','05月','07月','09月','12月'],height:195})}<p class="small muted">图表为固定布局样例，不是本因子的实际计算报告。正式画像还包括分层收益、单调性、换手、IC 衰减、行业分布和容量。</p>`,UI.button('导出定义','export-factor','default',`data-id="${f.id}"`)+UI.button(State.selectedFactors.has(f.id)?'从已选中移除':'加入已选因子','select-factor','primary',`data-id="${f.id}" ${f.status!=='已完成'?'disabled':''}`),true)}
function logModal(id){modal('任务日志 · '+escapeHTML(id),`<div class="notice notice-blue">日志仅为交互演示。真实后端将按 job_id 返回持续进度、分区状态和错误证据。</div><pre class="code" style="margin-top:17px">[PLAN] resolve input snapshot: market_0904
[PLAN] validate schema / available_at / partition range
[DEMO] checkpoint: partition=2025-11, attempt=1
[EXAMPLE] WARMUP_INSUFFICIENT: expected 60 prior trading days
[RECOVERY] expand read window; write only target partition
[PUBLISH] validate → commit manifest → expose new version
[LINEAGE] preserve previous published snapshot</pre>`,UI.button('关闭','close-modal'))}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action],[data-page]');if(!el)return;const a=el.dataset.action,id=el.dataset.id,v=el.dataset.value;if(el.dataset.page&&(!a||a==='navigate')){if(!overlay.hidden)closeModal();navigate(el.dataset.page,el.dataset.tab);return}
 switch(a){
 case 'close-modal':closeModal();break;
 case 'toggle-nav':document.body.classList.toggle('nav-open');break;
 case 'export-config':if(State.page==='intelligence'){window.handleExtraAction('intel-export-config',el)}else{download('quant-research-config.json',JSON.stringify(config(),null,2))}break;
 case 'search':modal('搜索页面与研究资产',`<input id="global-search" type="search" placeholder="输入页面名称或因子，例如：回测、动量" aria-label="全局搜索" style="width:100%;margin-bottom:15px"><div id="search-results">${navItems.map(x=>`<button class="search-result" data-page="${x[0]}"><span>${x[1]} &nbsp; ${x[2]}</span><span class="small muted">${x[3]}</span></button>`).join('')}</div>`);setTimeout(()=>document.getElementById('global-search')?.focus(),10);break;
 case 'new-research':modal('新建研究工作流',`<div class="form-grid">${UI.field('研究名称',UI.input('research-name','中证500 · 量价多因子研究'))}${UI.field('研究路径',UI.select('research-path',['因子合成基线','模型预测选股'],'模型预测选股'))}</div><div class="divider"></div><p class="small muted">从已有数据快照出发，逐步冻结因子集、样本切分、模型和策略版本。此操作只创建本地演示记录。</p>`,UI.button('取消','close-modal')+UI.button('创建并选择因子','create-research','primary'));break;
 case 'create-research':{const name=document.getElementById('research-name').value.trim();if(!name){toast('请填写研究名称');break;}State.researchName=name;pushTask(name,'研究草稿');closeModal();navigate('factors');toast('研究草稿已创建，先选择可用因子');break;}
 case 'data-tab':State.dataTab=v;render(true);break;
 case 'asset-detail':{const d=dataAssets[Number(id)];modal(d[0]+' · 结构与样例',`${UI.badge('字段契约示例 · 尚未接入','amber')}<div class="divider"></div>${UI.table(['字段','类型','含义'],[['instrument_id','string','证券唯一标识'],['trade_date','date','交易日'],['available_at','timestamp','源数据实际可知时间'],['snapshot_id','string','不可变数据快照'],[d[1]==='factor_values'?'factor_version':'source_revision','string','因子版本 / 源修订版本'],['value_status','enum','有效、缺失、待算等原因码']])}<div class="divider"></div><p class="small muted">设计目标：支持字段预览、样例行、质量报告、分区覆盖、下游引用和版本差异。真实映射需读取你现有工程的结构后确定。</p>`,UI.button('配置字段映射','connect-data','primary'),true);break;}
 case 'connect-data':modal('现有数据 · 字段映射设计',`<div class="notice notice-blue">当前仅保存配置草稿，不读取你的磁盘、数据库或服务。</div><div class="form-grid" style="margin-top:18px">${['证券代码|ts_code','交易日|trade_date','收盘价|close','成交量（股）|vol','成交额（元）|amount','实际可知时间|available_at'].map((s,i)=>{const x=s.split('|');return UI.field(x[0],UI.input('map-'+i,x[1]))}).join('')}</div><div class="divider"></div><p class="small muted">上线前校验成交量单位、价格精度、交易所编码和时间语义。若源文件缺少可知时间，不可默认以交易日代替财务公告时间。</p>`,UI.button('保存映射草稿','save-mapping','primary'));break;
 case 'save-mapping':State.mapping=Array.from(overlay.querySelectorAll('input')).map(x=>({field:x.id,source:x.value}));closeModal();toast('字段映射已保存在本次会话；尚未连接数据源');break;
 case 'quality-detail':modal('缺失分区 · 演示明细',UI.table(['区间','范围','缺失原因','影响'],[['2024-02','37 只证券日','源文件缺少记录','动量 / 波动率依赖'],['2024 Q4','财务公告字段','available_at 未映射','禁止 PIT 样本发布']])+`<div class="divider"></div><p class="small muted">修复流程：确认缺失原因 → 补齐源记录 → 重新校验 → 发布新快照 → 标记下游重算。</p>`,UI.button('配置补算','new-compute','primary'));break;
 case 'query-market':{const value=document.getElementById('market-security').value;const start=document.getElementById('market-start').value,end=document.getElementById('market-end').value;if(start>end){toast('起始日不能晚于结束日');break;}document.getElementById('market-chart').innerHTML=UI.lineChart({series:[{name:value+' · 查询区间布局示例',values:demoStrategy.map(n=>n*(value.includes('B')?8:10)),color:'#34987a'}],labels:[start,end],height:280});toast('已更新示例图；演示行不会查询真实行情');break;}
 case 'factor-category':State.factorCategory=v;render(true);break;
 case 'factor-detail':factorDetail(id);break;
 case 'export-factor':download(id+'-definition.json',JSON.stringify({prototype:true,...FACTORS.find(f=>f.id===id)},null,2));break;
 case 'select-factor':State.selectedFactors.has(id)?State.selectedFactors.delete(id):State.selectedFactors.add(id);invalidate('factors');closeModal();render(true);toast('已更新因子选择');break;
 case 'run-selection':State.selectionRan=true;State.selectionIds=getSelectionCandidates().map(f=>f.id);render(true);toast('本地条件筛选完成；稳健性和验证仍需真实计算');break;
 case 'save-feature-set':{const ids=State.selectionRan?State.selectionIds:[...State.selectedFactors];if(!ids?.length){toast('当前没有可保存的因子，请调整筛选条件');break;}State.selectedFactors=new Set(ids);State.featureSetSaved=true;invalidate('factors');modal('特征集草稿 · 已保存',`${UI.badge('待正式验证','amber')}<p style="margin-top:13px">${ids.length} 个因子已保存到本次研究会话。</p><pre class="code">${escapeHTML(ids.map(id=>{const f=FACTORS.find(x=>x.id===id);return f.id+'@'+f.version+' · '+f.direction}).join('\n'))}</pre><p class="small muted">正式系统需要质量与研究验证通过后，才能发布不可变的特征集版本。这里可继续评审样本构建流程。</p>`,UI.button('导出配置','export-config')+`<button class="btn btn-primary" data-page="dataset">配置样本与标签 →</button>`);break;}
 case 'save-factor-definition':{const name=document.getElementById('compute-factor-name').value.trim(),formula=document.getElementById('compute-formula').value.trim();if(!name||!formula){toast('名称与表达式不能为空');break;}State.factorDraft={name,formula};toast('定义草稿已保存；公式解析与依赖检查由后端实现');break;}
 case 'new-compute':modal('创建计算任务 · 配置预览',`<div class="form-grid">${UI.field('模式',UI.select('job-mode',['日增量计算','历史回填','失败分区重算'],'历史回填'))}${UI.field('因子范围',UI.input('job-factor',State.factorDraft?.name||'20日动量 / mom20'))}${UI.field('目标起始日',UI.input('job-start','2023-01-03','date'))}${UI.field('目标结束日',UI.input('job-end','2026-09-04','date'))}${UI.field('分片粒度',UI.select('job-partition',['按月','按日'],'按月'))}${UI.field('最大并发数',UI.input('job-workers',4,'number'))}</div><div class="notice notice-amber" style="margin-top:18px">读取区间自动包含因子预热窗口；发布只覆盖目标区间。当前只创建演示任务。</div>`,UI.button('创建演示任务','submit-compute','primary'));break;
 case 'submit-compute':{const start=document.getElementById('job-start').value,end=document.getElementById('job-end').value,workers=Number(document.getElementById('job-workers').value);if(!start||!end||start>end||workers<1||workers>64||!Number.isInteger(workers)){toast('请检查日期范围和并发数（1—64 的整数）');break;}pushTask(document.getElementById('job-factor').value+' · '+document.getElementById('job-mode').value,'因子计算','演示已排队');closeModal();navigate('tasks');toast('演示任务已进入队列，未启动真实计算');break;}
 case 'retry-compute':State.computeRetried=true;pushTask('失败分区 · 扩展预热后重试','因子计算','演示已排队');render(true);toast('已创建演示重试任务；原失败记录保留');break;
 case 'compute-log':case 'task-log':logModal(id);break;
 case 'task-filter':State.taskFilter=v;render(true);break;
 case 'retry-task':pushTask(id+' · 重试','因子计算','演示已排队');render(true);toast('演示重试已排队，原记录保留');break;
 case 'cancel-task':{const t=State.tasks.find(x=>x.id===id);if(t)t.status='演示已取消';else State.tasks.unshift({id:id+'-CANCEL',name:id+' · 取消请求已记录',type:'控制记录',status:'演示已取消',progress:0});render(true);toast('已记录取消请求；后端应在安全边界停止');break;}
 case 'save-dataset':{const d=State.dataset;const dates=[d.trainStart||'2021-01-04',d.trainEnd||'2023-12-29',d.validStart||'2024-01-02',d.validEnd||'2024-12-31',d.testStart||'2025-01-02',d.testEnd||'2025-12-31'];if(!State.selectedFactors.size){toast('至少选择一个可用因子');break;}if(dates.some((x,i)=>i&&x<=dates[i-1])){toast('训练、验证和测试日期必须有序且互不重叠');break;}State.datasetSaved=true;State.datasetFrozen=JSON.parse(JSON.stringify(d));pushTask((d.version||'ds_research_v003')+' · 配置冻结演示','数据构建');render(true);toast('数据集配置已冻结为演示版本；未生成真实样本矩阵');break;}
 case 'run-training':{const m=State.model;if(m.algorithm==='LightGBM'&&(!(Number(m.learningRate)>0&&Number(m.learningRate)<=1)||Number(m.leaves)<2||Number(m.rounds)<10)){toast('请检查学习率、叶子数和训练轮次');break;}if(!State.selectedFactors.size){toast('请先选择因子');break;}State.experimentCreated=true;State.experimentConfig=config();pushTask('新训练配置 · '+m.algorithm,'模型训练');render(true);toast('已保存训练配置演示；下方展示固定 EXP-024 示例结果');break;}
 case 'training-tab':State.trainingTab=v;render(true);break;
 case 'register-model':State.modelRegistered=true;render(true);toast('已注册示例 EXP-024 模型引用，尚无真实模型文件');break;
 case 'save-strategy':{const p=State.strategy;if(p.source==='因子合成'&&Math.abs(Number(p.factorMOM??40)+Number(p.factorVOL??30)+Number(p.factorREV??30)-100)>.0001){toast('合成权重必须合计 100%');break;}if(!(Number(p.topk)>=5&&Number(p.topk)<=200)||Number(p.stockCap)<=0||Number(p.industryCap)<=0){toast('请检查持股数及权重上限');break;}State.strategySaved=true;State.strategyFrozen=JSON.parse(JSON.stringify(p));render(true);toast('策略配置已保存为本地演示版本');break;}
 case 'preview-strategy':render(true);toast('已更新配置结构预览；选股分数仍为固定示例');break;
 case 'backtest-tab':State.backtestTab=v;render(true);break;
 case 'run-backtest':{const b=State.backtest||{};if(b.start&&b.end&&b.start>b.end){toast('回测起始日不能晚于结束日');break;}if(b.capital&&Number(b.capital)<=0){toast('初始资金必须大于零');break;}State.backtestCreated=true;State.backtestFrozen=config();pushTask('回测配置预览 · '+(b.benchmark||'中证500'),'策略回测');render(true);toast('已记录演示配置；收益报告仍为固定样例，不随参数重算');break;}
 case 'export-backtest':download('backtest-config-demo.json',JSON.stringify(State.backtestFrozen||config(),null,2));break;
 case 'export-trades':download('trades-demo.csv','\ufeff日期,标的,方向,目标数量,成交数量,状态,原因\n2025-12-26,DEMO001,买入,1000,1000,成交,开盘价加滑点示例\n2025-12-26,DEMO002,买入,2000,0,未成交,涨停封板\n2025-12-26,DEMO003,卖出,1200,0,未成交,停牌\n','text/csv;charset=utf-8');break;
 default:if(window.handleExtraAction?.(a,el))break;toast('此项为后续实现设计，可在系统蓝图中查看约定');}
});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.factor){el.checked?State.selectedFactors.add(el.dataset.factor):State.selectedFactors.delete(el.dataset.factor);invalidate('factors');render(true);return}if(el.id==='factor-sort'){State.factorSort=el.value;render(true);return}if(el.id==='selection-role'){State.selectionRole=el.value;State.selectionRan=false;State.selectionIds=undefined;render(true);return}if(el.id==='selection-threshold'){State.selectionThreshold=Number(el.value);State.selectionRan=false;State.selectionIds=undefined;render(true);return}const parts=el.id?.match(/^(dataset|model|strategy|backtest)-(.+)$/);if(parts){const [,scope,key]=parts;State[scope]??={};State[scope][key]=el.type==='checkbox'?el.checked:el.value;invalidate(scope);render(true)}});
document.addEventListener('input',e=>{if(e.target.id==='factor-search'){const pos=e.target.selectionStart;State.factorQuery=e.target.value;render(true);const n=document.getElementById('factor-search');n.focus();n.setSelectionRange(pos,pos)}if(e.target.id==='global-search'){const q=e.target.value.trim().toLowerCase();document.getElementById('search-results').innerHTML=navItems.filter(x=>(x[2]+x[3]).includes(q)).map(x=>`<button class="search-result" data-page="${x[0]}">${x[2]}<span class="small muted">页面 →</span></button>`).join('')+FACTORS.filter(f=>(f.id+f.name).toLowerCase().includes(q)).slice(0,6).map(f=>`<button class="search-result" data-action="factor-detail" data-id="${f.id}">${f.name}<span class="small muted">因子 →</span></button>`).join('')}});
overlay.addEventListener('click',e=>{if(e.target===overlay)closeModal()});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('[data-action="search"]').click()}if(e.key==='Escape'){closeModal();document.body.classList.remove('nav-open')}if(e.key==='Tab'&&!overlay.hidden){const els=[...overlay.querySelectorAll('button:not(:disabled),input,select,textarea,a[href]')];const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)||'overview'));
navigate(location.hash.slice(1)||'overview');
