/* Merge published backend assets into the existing design; preserve all workflow pages. */
(() => {
 const U=UI,E=escapeHTML,storeKey='quant-backend-selection-v2',definitionKey='quant-factor-definition-v2';
 let source=null,quality=null,loadError='',qualityError='',loading=false,sourceReport=null;
 const qualityApiUrl='http://127.0.0.1:8770/api/v1/quality/overview';
 let definition={name:'60 日复权动量',factor_id:'price-momentum-60',factor_version:'1.0.0',formula:'adjusted_close / Ref(adjusted_close, 60) - 1',family:'momentum',direction:'POSITIVE',hypothesis:'检验中期趋势延续假设',mode:'custom',profile:'m4.2',start:'2024-01-02',end:'2024-03-29',variant:'RAW'};
 try{const d=JSON.parse(localStorage.getItem(definitionKey));if(d&&typeof d==='object')definition={...definition,...d}}catch{}
 const originalPages={...Pages},oldDetail=factorDetail,oldConfig=config;
 const num=(v,d=4)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'—';
 const count=v=>typeof v==='number'?v.toLocaleString('zh-CN'):'—';
 const date=v=>v?E(new Date(v).toLocaleString('zh-CN',{hour12:false})):'—';
 const json=v=>`<pre class="code be-json">${E(JSON.stringify(v,null,2))}</pre>`;
 const btn=(t,a,more='')=>`<button class="btn" data-be="${a}" ${more}>${t}</button>`;
 const tag=t=>U.badge(E(t||'未提供'),'blue');
 const r=()=>source?.evidence.report||{};
 const selected=()=>source?.evidence.factors.filter(f=>State.selectedFactors.has(f.entity_id))||[];
 const fields=['open','high','low','close','volume_shares','adjusted_open','adjusted_close','return_1d','illiquidity_1d','pb','pe_ttm','total_mv','roe','debt_to_assets'];
 function saveSelection(){if(!source)return;try{localStorage.setItem(storeKey,JSON.stringify({report_id:sourceReport,entities:[...State.selectedFactors]}))}catch{toast('浏览器存储不可用，请导出配置留存')}}
 function binding(){return {report_id:sourceReport,current_report_id:r().report_id,source_root:source?.source_root,label:{id:r().label_id,version:r().label_version,release_id:r().label_release_id},universe:{id:r().universe_id,version:r().universe_version},sample_classification:r().sample_classification,features:selected().map(f=>({entity_id:f.entity_id,factor_id:f.factor_id,factor_version:f.factor_version,variant:f.variant,implementation_hash:f.implementation_hash,release_id:f.quality?.release_id})),limitations:r().limitations}}
 config=function(){return {...oldConfig(),backend_inputs:source?binding():null,execution_status:'CONFIGURATION_ONLY_NOT_EXECUTED'}};
 function banner(){return `<section class="be-source"><div><strong>${source?'已合并后端产物':'后端产物接入'}</strong><span>${source?'报告 '+date(r().generated_at)+' · 本次读取 '+date(source.read_at):'连接中；原设计链条保持可用'}</span></div><div>${btn('刷新','refresh')}${btn('来源','sources')}</div></section>${loadError?`<div class="notice notice-amber" role="alert">${E(loadError)}；${source?'保留上次成功快照':'当前页面仅有原设计样例'}。</div>`:''}${sourceReport&&sourceReport!==r().report_id?`<div class="notice notice-amber">候选集绑定旧报告，当前展示新报告。${btn('清空候选并绑定新报告','rebind')}</div>`:''}`}
 function ingestion(){return U.table(['采集流','文件记录状态','进度 / 产物','最近更新'],source.ingestion.map(t=>[E(t.name.replace('tushare_','')),tag(t.status),t.expected_partitions?`${count(t.completed_partitions)} / ${count(t.expected_partitions)} 分区<br>${E(t.api_name)} · ${E(t.partition)}`:Object.entries(t.summary?.totals||{}).map(([k,v])=>E(k)+': '+count(v.rows)+' 行').join('<br>'),date(t.updated_at)+(t.status==='RUNNING'&&Date.now()-Date.parse(t.updated_at)>300000?'<br>心跳超过 5 分钟，需核查进程':'')]));}
 function releases(){return U.card('现有工程 · 因子发布批次','独立发布版本；不同窗口或处理变体的行数不累加',U.table(['版本','处理变体','计算窗口','因子 / 证券','行数','质量'],source.releases.map(m=>[E(m.release_id?.slice(7,19)),E(m.request?.variant),E(m.request?.start)+' → '+E(m.request?.end),count(m.factor_count)+' / '+count(m.instrument_count),count(m.row_count),tag(m.quality_status)])),btn('配置现有计算流程','configure'));}
 function auditBadge(ok,warning=false){return U.badge(ok?(warning?'通过 · 有发现':'通过'):'需处理',ok?(warning?'amber':'green'):'red')}
 function coverageRow(label,start,end,year){const begin=new Date(start),finish=new Date(end);return `<span>${E(label)}</span>${Array.from({length:12},(_,month)=>{const first=new Date(`${year}-${String(month+1).padStart(2,'0')}-01T00:00:00`),last=new Date(year,month+1,0);const covered=begin<=last&&finish>=first;return `<div class="heat-cell ${covered?'be-covered':'empty'}" title="${E(label)}：${E(start)} → ${E(end)}；此格表示报告区间覆盖，不代表逐月完整性检查"></div>`}).join('')}`}
 function qualityPage(){
  const w=source.warehouse||{},a=source.audits||{},ref=a.reference||{},corp=a.corporate_actions||{},fin=a.financial||{},factor=a.factor_release||{};
  const tables=Object.values(w.tables||{}),duplicates=tables.reduce((sum,item)=>sum+(item.duplicate_keys||0),0),nullKeys=tables.reduce((sum,item)=>sum+(item.null_keys||0),0),ohlc=w.tables?.daily?.invalid_ohlc||0;
  const pitExceptions=Object.values(fin.pit_exception_counts||{}).reduce((sum,value)=>sum+value,0),quarantined=corp.approval_gate?.matched_but_quarantined||0;
  const factorRows=source.evidence.factors||[],lowCoverage=factorRows.filter(item=>(item.basic_evidence?.mean_coverage??0)<.98),integrity=(factor.duplicate_key_count||0)+(factor.outside_universe_count||0)+(factor.clock_error_count||0)+(factor.quality_summary?.nonfinite_count||0);
  const auditRows=[
   ['行情主键','daily / adj_factor / daily_basic',auditBadge(duplicates===0),`${count(duplicates)} 个重复键；${count(nullKeys)} 个空键`],
   ['行情价格关系','research.market_daily_anomalies',auditBadge(true,ohlc>0),`${count(ohlc)} 条供应商 OHLC 异常已隔离；可交易视图 ${count(w.tables?.daily?.tradable_view_rows)} 行`],
   ['成交量与成交额','daily',auditBadge((w.tables?.daily?.negative_volume||0)===0&&(w.tables?.daily?.negative_amount||0)===0),`负成交量 ${count(w.tables?.daily?.negative_volume)}；负成交额 ${count(w.tables?.daily?.negative_amount)}`],
   ['历史证券状态','security_session_state',auditBadge((ref.security_session_state?.duplicate_keys||0)===0,true),`${count(ref.security_session_state?.unknown_st_rows)} 行早期 ST 状态未知；退市后记录 ${count(ref.security_session_state?.after_delisting_rows)}`],
   ['财务可知时间','四类财务版本表',auditBadge((fin.failures||[]).length===0,pitExceptions>0),`${count(pitExceptions)} 条 PIT 例外已登记；${count(fin.canonical_count)} 条规范版本`],
   ['公司行动对账','股息事件 × 复权因子',auditBadge((corp.failures||[]).length===0,quarantined>0),`${count(quarantined)} 条匹配记录隔离；${count(corp.approval_gate?.approved_dividend_adjustments)} 条获准调整`],
   ['因子发布完整性','主键 / 股票池 / 时钟 / 非有限值',auditBadge(integrity===0),`${count(integrity)} 个完整性错误；发布审计 ${E(factor.status||'未提供')}`],
   ['因子基础覆盖率','各实体 basic_evidence 独立窗口',auditBadge(lowCoverage.length===0,lowCoverage.length>0),`${count(lowCoverage.length)} / ${count(factorRows.length)} 个变体低于 98%；不跨窗口拼接`]
  ];
  const year=Number((r().window?.end||w.tables?.daily?.max_trade_date||'2025').slice(0,4));
  const statusRows=[['行情审计',w.status,w.audited_at,(w.warnings||[]).length],['参考与股票池',ref.status,ref.audited_at,(ref.warnings||[]).length],['公司行动',corp.status,corp.audited_at,(corp.warnings||[]).length],['财务 PIT',fin.status,fin.audited_at,(fin.failures||[]).length],['因子发布',factor.status,factor.audited_at,(factor.failures||[]).length]];
  const ranges={market:[w.tables?.daily?.min_trade_date,w.tables?.daily?.max_trade_date],reference:[ref.calendar?.min_date,ref.calendar?.max_date],financial:[source.ingestion.find(x=>x.name==='tushare_financial_archive')?.summary?.coverage?.start,source.ingestion.find(x=>x.name==='tushare_financial_archive')?.summary?.coverage?.end],factors:[r().window?.start,r().window?.end]};
  return `<div class="stack be-real-quality">
   <div class="grid-3">${U.metric('实际审计域','5','行情、参考、公司行动、财务、因子')}${U.metric('完整性错误',count(integrity+duplicates+nullKeys),'重复、空键、越池、时钟、非有限值')}${U.metric('隔离 / 例外',count(ohlc+quarantined+pitExceptions),`${count(ohlc)} OHLC · ${count(quarantined)} 公司行动 · ${count(pitExceptions)} PIT`)}</div>
   ${U.card('真实数据质量检查','读取后端审计 JSON；结果绑定各自审计时间，不是前端重新扫描数据库',U.table(['检查项','实际范围','审计结果','真实记录'],auditRows))}
   ${U.card(`${year} 年报告区间覆盖`,'绿色表示已发布报告的起止区间包含该月份，不代表该月每个分区都已逐项核验',`<div class="heat-grid"><span>${year} 年</span>${Array.from({length:12},(_,i)=>`<span>${i+1}月</span>`).join('')}${coverageRow('日行情',...ranges.market,year)}${coverageRow('参考数据',...ranges.reference,year)}${coverageRow('财务归档',...ranges.financial,year)}${coverageRow('因子证据',...ranges.factors,year)}</div><div class="be-legend"><span><i class="be-swatch be-ok"></i>报告区间覆盖</span><span><i class="be-swatch be-none"></i>报告区间未覆盖</span></div>`)}
   <div class="grid-2">${U.card('审计批次与时点','每类数据使用独立审计，不用当前页面时间冒充审计完成时间',U.table(['审计域','状态','审计时间','发现 / 失败'],statusRows.map(row=>[E(row[0]),tag(row[1]),date(row[2]),count(row[3])])))}${U.card('待复核的真实发现','这些记录已在后端审计中显式保留，不会被“通过”状态隐藏',U.table(['来源','发现'],[['行情',`${count(ohlc)} 条供应商 OHLC 异常已从可交易视图隔离`],['参考数据',`${count(ref.security_session_state?.unknown_st_rows)} 行早期 ST 状态未知；${count(ref.security_session_state?.current_name_fallback_rows)} 行使用当前名称回退`],['公司行动',`${count(quarantined)} 条匹配但隔离；${count(corp.diagnostic_statuses?.UNEXPLAINED_PRICE_ADJUSTMENT)} 条未解释价格调整`],['财务 PIT',`${count(fin.pit_exception_counts?.AVAILABLE_BEFORE_PERIOD_END)} 条早于期末；${count(fin.pit_exception_counts?.MISSING_AVAILABLE_DATE)} 条缺少可知日期`],['因子覆盖',lowCoverage.length?lowCoverage.slice(0,8).map(x=>`${E(x.factor_id)} · ${E(x.variant)} ${num((x.basic_evidence?.mean_coverage||0)*100,2)}%`).join('<br>'):'全部实体基础窗口覆盖率 ≥ 98%']]))}</div>
   <p class="small muted">来源：warehouse_audit、m2b/m2c/m2d audit、m3_2_factor_release_audit、当前 Factor Explorer。读取时间 ${date(source.read_at)}。</p>
  </div>`;
 }
 function qualityFact(check){const f=check.facts||{};switch(check.id){
  case 'market_keys':return `${count(f.duplicate_keys)} 个重复键；${count(f.null_keys)} 个空键`;
  case 'market_prices':return `${count(f.isolated_invalid_ohlc)} 条供应商 OHLC 异常已隔离；可交易视图 ${count(f.tradable_rows)} 行`;
  case 'market_volume':return `负成交量 ${count(f.negative_volume)}；负成交额 ${count(f.negative_amount)}`;
  case 'security_state':return `${count(f.unknown_st_rows)} 行早期 ST 状态未知；退市后记录 ${count(f.after_delisting_rows)}`;
  case 'financial_pit':return `${count(f.pit_exceptions)} 条 PIT 例外已登记；${count(f.canonical_versions)} 条规范版本`;
  case 'corporate_actions':return `${count(f.quarantined_matches)} 条匹配记录隔离；${count(f.approved_adjustments)} 条获准调整`;
  case 'factor_integrity':return `${count(f.integrity_errors)} 个完整性错误；发布审计 ${E(f.audit_status)}`;
  case 'factor_coverage':return `${count(f.below_98_percent)} / ${count(f.entity_count)} 个变体低于 98%；不跨窗口拼接`;
  default:return json(f);
 }}
 function apiStatus(value){return U.badge(value==='PASS'?'通过':value==='PASS_WITH_FINDINGS'?'通过 · 有发现':'需处理',value==='PASS'?'green':value==='PASS_WITH_FINDINGS'?'amber':'red')}
 function qualityApiPage(){
  if(!quality)return `<div class="stack be-real-quality"><div class="notice notice-amber" role="alert">${E(qualityError||'正在连接后端质量接口')}。原示例数据不会作为替代结果显示。</div>${U.card('质量接口','前后端独立运行',`<p>接口：<span class="mono">${E(qualityApiUrl)}</span></p><p class="small muted">启动后端：powershell -ExecutionPolicy Bypass -File scripts/start_research_api.ps1</p>${btn('重新请求','refresh')}`)}</div>`;
  const s=quality.summary,year=Number((quality.report_window?.end||'2025').slice(0,4));
  const checkRows=quality.checks.map(item=>[E(item.name),E(item.scope),apiStatus(item.status),qualityFact(item)]);
  const coverageRows=quality.coverage.map(item=>coverageRow(item.name,item.start,item.end,year)).join('');
  const batchRows=quality.audit_batches.map(item=>[E(item.name),tag(item.status),date(item.audited_at),`${count(item.finding_count)} / ${count(item.failure_count)}`]);
  const checks=Object.fromEntries(quality.checks.map(item=>[item.id,item.facts||{}]));
  const low=quality.low_coverage_entities||[];
  return `<div class="stack be-real-quality">
   <div class="be-api-state"><span class="be-live-dot"></span><strong>后端质量接口</strong><span>${date(quality.generated_at)} 实时生成 · ${E(quality.report_id?.slice(0,19))}</span><span class="mono">GET /api/v1/quality/overview</span></div>
   ${qualityError?`<div class="notice notice-amber" role="alert">${E(qualityError)}；保留上次成功响应，时间见上方。</div>`:''}
   <div class="grid-3">${U.metric('实际审计域',count(s.audit_domain_count),'行情、参考、公司行动、财务、因子')}${U.metric('完整性错误',count(s.integrity_error_count),'重复、空键、越池、时钟、非有限值')}${U.metric('隔离 / 例外',count(s.isolated_or_exception_count),`${count(s.invalid_ohlc_count)} OHLC · ${count(s.quarantined_corporate_action_count)} 公司行动 · ${count(s.pit_exception_count)} PIT`)}</div>
   ${U.card('真实数据质量检查','浏览器直接请求后端 8770；每次刷新均重新读取当前审计产物',U.table(['检查项','实际范围','审计结果','真实记录'],checkRows))}
   ${U.card(`${year} 年报告区间覆盖`,'绿色表示后端返回的报告起止区间包含该月份，不代表逐月完整性已核验',`<div class="heat-grid"><span>${year} 年</span>${Array.from({length:12},(_,i)=>`<span>${i+1}月</span>`).join('')}${coverageRows}</div><div class="be-legend"><span><i class="be-swatch be-ok"></i>报告区间覆盖</span><span><i class="be-swatch be-none"></i>报告区间未覆盖</span></div>`)}
   <div class="grid-2">${U.card('审计批次与时点','审计时间由后端各报告提供；发现数 / 失败数分开显示',U.table(['审计域','状态','审计时间','发现 / 失败'],batchRows))}${U.card('待复核的真实发现','所有数字来自本次 API 响应',U.table(['来源','发现'],[['行情',`${count(checks.market_prices?.isolated_invalid_ohlc)} 条供应商 OHLC 异常已从可交易视图隔离`],['参考数据',`${count(checks.security_state?.unknown_st_rows)} 行早期 ST 状态未知；${count(checks.security_state?.current_name_fallback_rows)} 行使用当前名称回退`],['公司行动',`${count(checks.corporate_actions?.quarantined_matches)} 条匹配但隔离；${count(checks.corporate_actions?.unexplained_price_adjustments)} 条未解释价格调整`],['财务 PIT',`${count(checks.financial_pit?.pit_exceptions)} 条已登记例外`],['因子覆盖',low.length?low.slice(0,8).map(item=>`${E(item.factor_id)} · ${E(item.variant)} ${num(item.coverage*100,2)}%`).join('<br>'):'全部实体基础窗口覆盖率 ≥ 98%']]))}</div>
   <details><summary>接口响应来源版本</summary>${json({generated_at:quality.generated_at,source_versions:quality.source_versions,warnings:quality.warnings})}</details>
  </div>`;
 }
 function panel(page){if(!source)return '';const s=source.evidence.summary,w=source.warehouse;
 if(page==='overview')return U.card('现有工程 · 数据与因子进展','真实发布产物已进入下方研究链条；原有模型、策略和回测样例继续保留',`<div class="grid-4">${U.metric('行情审计行数',count(w?.tables?.daily?.row_count),'截至 '+E(w?.tables?.daily?.max_trade_date))}${U.metric('因子 / 变体',`${s.factor_count} / ${s.entity_count}`,'RAW 与预处理版本')}${U.metric('去重路径 / 簇',`${s.canonical_count} / ${s.cluster_count}`,'机械聚类，不等于策略准入')}${U.metric('执行证据',count(s.execution_available_count),'训练、回测尚待接入')}</div>`);
 if(page==='data')return U.card('现有工程 · 数据资产与采集','保留资产 / 行情 / 质量 / 接入四个原有视图；此区来自已发布审计和采集记录',`${U.table(['表','行数','日期覆盖','重复主键','异常 OHLC'],Object.entries(w?.tables||{}).map(([k,v])=>[E(k),count(v.row_count),E(v.min_trade_date)+' → '+E(v.max_trade_date),count(v.duplicate_keys),count(v.invalid_ohlc)]))}<p class="small muted">审计时点 ${date(w?.audited_at)}。${(w?.warnings||[]).map(E).join('；')}</p><details><summary>真实行情样例 · 审计文件记录</summary>${U.table(['证券','日期','收盘 / 元','成交量 / 股','成交额 / 元'],(w?.sample_000001_sz||[]).map(row=>row.map(E)))}</details><details><summary>现有采集状态 · 不改变采集任务</summary>${ingestion()}</details>`);
 if(page==='compute')return releases();
 if(page==='factors')return `<div class="notice notice-blue">原有因子目录已装入 ${s.factor_count} 个真实因子的 ${s.entity_count} 个变体。IC / 覆盖率使用各实体 basic_evidence 窗口；ICIR 未提供则留空。用途暂按“预测”用于配置草稿，非后端准入结论。</div>`;
 if(page==='selection')return U.card('现有工程 · 因子冗余证据','上方选中的真实因子沿原有特征筛选流程传递；下方相关性矩阵仍是原设计示意',`<div class="toolbar">${tag(s.canonical_count+' 条规范路径')}${tag(s.cluster_count+' 个簇')}${tag('已选 '+selected().length+' 个真实实体')}</div><details><summary>查看真实簇与机械代表</summary>${U.table(['簇','成员数','代表','证据'],(source.evidence.clusters||[]).map(c=>[E(c.cluster_id),count(c.members?.length),E(c.representative_entity_id),btn('画像','detail',`data-id="${E(c.representative_entity_id)}"`)]))}</details>`);
 if(['dataset','training','strategy','backtest','monitor'].includes(page))return U.card('现有工程 · 当前研究输入','沿用原有样本 → 模型 / 因子合成 → 策略 → 回测 → 模拟链条；下方配置和样例报告保持原设计',`<div class="toolbar">${tag('真实候选 '+selected().length+' 项')}${tag(r().universe_id)}${tag('标签 '+r().label_horizon_sessions+' 个交易日')}</div><p class="small muted">${E(r().window?.start)} → ${E(r().window?.end)} 已暴露研究样本；既有滚动检验不作为新的未见样本外验证。真实输入会随原有“导出配置”一并导出，尚未执行训练或回测。</p><details><summary>已绑定因子、标签与版本</summary>${json(binding())}</details>${page==='dataset'?`<details><summary>后端既有滚动样本切分</summary>${U.table(['Fold','训练','验证','测试','Purge / Embargo'],(source.pipeline?.config?.walk_forward?.folds||[]).map(f=>[E(f.fold_id),E(f.train_start)+' → '+E(f.train_end),E(f.validation_start)+' → '+E(f.validation_end),E(f.test_start)+' → '+E(f.test_end),E(f.purge_sessions)+' / '+E(f.embargo_sessions)]))}</details>`:''}`);
 if(page==='tasks')return U.card('现有工程 · 真实采集与研究批次','原有统一任务队列设计保留在下方；真实记录不提供未接入的重试或取消操作',`${ingestion()}<details><summary>最近研究流水线</summary>${U.table(['阶段','完成时间','审计结果'],Object.entries(source.pipeline?.stages||{}).map(([k,v])=>[E(k),date(v.completed_at),tag(v.result?.status||(v.completed_at?'已记录完成':'未记录完成'))]))}</details>`);
 return '';
 }
 function decorate(page,html){const template=document.createElement('template');template.innerHTML=html;
 // Insert within the established workflow header and handoff rather than replacing it.
 const guide=template.content.querySelector('.qf-guide');const extra=banner()+panel(page);if(guide)guide.insertAdjacentHTML('afterend',extra);else{const container=document.createElement('div');container.innerHTML=extra;template.content.prepend(...container.childNodes)}
 if(source&&page==='factors'){
 const metrics=template.content.querySelector('.factor-view .grid-4');if(metrics)metrics.innerHTML=U.metric('真实因子定义',count(source.evidence.summary.factor_count),'按因子 ID 去重')+U.metric('已发布变体',count(FACTORS.length),'每行保留处理变体与版本')+U.metric('覆盖率达标',count(FACTORS.filter(f=>f.coverage>=98).length),'基础窗口 ≥ 98%；不是有效性结论')+U.metric('已选候选',count(State.selectedFactors.size),'沿原有研究链路传递');
 const notice=template.content.querySelector('.factor-view .notice');if(notice)notice.innerHTML='<b>先看可用性，再看有效性。</b> 当前目录为真实发布结果；筛选仅建立研究草稿。';
 const cards=template.content.querySelectorAll('.factor-view .grid-3 .card');if(cards[1])cards[1].querySelector('.card-body').innerHTML='<p class="small muted">IC 与覆盖率来自各因子的基础证据窗口，详见画像；未提供 ICIR 的实体显示 —。不跨窗口拼接指标。</p>';
 }
 if(page==='compute'){
 if(source){const metrics=template.content.querySelector('.factor-view .grid-4');if(metrics)metrics.innerHTML=U.metric('真实因子定义',count(source.evidence.summary.factor_count),'当前报告的独立因子')+U.metric('已发布批次',count(source.releases.length),'原始与预处理发布清单')+U.metric('正在计算','—','未接入因子任务状态接口')+U.metric('预处理批次',count(source.releases.filter(m=>m.kind==='processed_releases').length),'独立发布，不覆盖原值');}
 const view=template.content.querySelector('.factor-view');if(view)view.insertAdjacentHTML('afterbegin','<div class="notice notice-amber">下方保留原有计算布局：定义工作台可编辑真实草稿；分区热图、依赖图和 CALC 批次仍为设计样例。真实发布批次见上方。</div>');
 const name=template.content.querySelector('#compute-factor-name'),formula=template.content.querySelector('#compute-formula');if(name)name.value=definition.name;if(name)name.setAttribute('value',definition.name);if(formula)formula.textContent=definition.formula;
 const def=name?.closest('.card');if(def){const sub=def.querySelector('.card-head p');if(sub)sub.textContent='保留定义工作台 · 支持从后端已有公式创建新版本草稿';const bar=def.querySelector('.toolbar');if(bar)bar.insertAdjacentHTML('afterbegin',btn('从已有因子载入','template'))}
 }
 if(page==='selection'&&source){
 const universe=template.content.querySelector('#selection-universe'),label=template.content.querySelector('#selection-label');if(universe)universe.innerHTML='<option>'+E(r().universe_id)+' · 已有证据股票池</option>';if(label)label.innerHTML='<option>'+E(r().label_id)+' · 已有证据标签</option>';
 const run=template.content.querySelector('[data-action="run-selection"]');if(run)run.textContent='运行本地候选初筛';
 const view=template.content.querySelector('.factor-view');if(view)view.insertAdjacentHTML('afterbegin','<div class="notice notice-blue">本地初筛使用已发布 basic_evidence 的 IC 和覆盖率，只生成待验证候选。下方训练切分、相关矩阵和排除原因仍为原设计示意，不会据此重算真实指标。</div>');
 }
 if(page==='data'&&source&&State.dataTab==='quality'){
  const tabs=[...template.content.querySelectorAll('[data-action="data-tab"]')];
  const qualityTab=tabs.find(item=>item.dataset.value==='quality');
  const dataStack=qualityTab?.closest('.stack');
  if(dataStack){[...dataStack.children].filter(child=>!child.classList.contains('tabs')).forEach(child=>child.remove());dataStack.insertAdjacentHTML('beforeend',qualityApiPage())}
 }
 return template.innerHTML;
 }
 for(const page of ['overview','data','compute','factors','selection','dataset','training','strategy','backtest','monitor','tasks'])Pages[page]=()=>decorate(page,originalPages[page]());
 factorDetail=function(id){const f=source?.evidence.factors.find(f=>f.entity_id===id);if(!f)return oldDetail(id);const b=f.basic_evidence||{};modal(E(f.name)+' · '+E(f.variant),`<div class="toolbar">${tag(f.family)}${tag(f.lifecycle)}${tag(f.direction)}</div><p>${E(f.economic_hypothesis)}</p><pre class="code">${E(f.formula)}</pre><div class="grid-3">${U.metric('基础原始 IC',num(b.mean_rank_ic),'未调整方向')}${U.metric('基础覆盖率',typeof b.mean_coverage==='number'?num(b.mean_coverage*100,2)+'%':'—','同一基础评估窗口')}${U.metric('评估交易日',count(b.sessions),E(b.window?.start)+' → '+E(b.window?.end))}</div>${U.card('真实滚动证据','已运行后的窗口均为暴露研究样本',U.table(['Fold','训练 IC','验证 IC','测试原始 IC','HAC q','方向结论'],(f.folds||[]).map(x=>[E(x.fold_id),num(x.train_mean_rank_ic),num(x.validation_mean_rank_ic),num(x.test_mean_rank_ic_raw),num(x.hac_bh_q_value),E(x.hac_direction_outcome)])))}${U.card('真实增量证据','控制其他簇代表后的诊断',U.table(['项目','结果'],[['规范实体',E(f.deduplication?.canonical_entity_id)],['条件 Rank IC',num(f.incremental?.mean_conditional_rank_ic)],['增量 R²',num(f.incremental?.mean_incremental_r_squared)],['结论',E(f.incremental?.strict_incremental_outcome)],['执行证据',E(f.execution?.reason)]]))}<details><summary>完整后端实体</summary>${json(f)}</details>`,U.button(State.selectedFactors.has(id)?'移出已选':'加入已选因子','select-factor','primary',`data-id="${E(id)}" ${!(b.mean_coverage>=.98)?'disabled':''}`)+btn('以此创建新因子','clone',`data-id="${E(id)}"`),true)};
 function validate(){const errors=[];if(!definition.name.trim())errors.push('请填写因子名称');if(!/^[a-z][a-z0-9-]{1,79}$/.test(definition.factor_id))errors.push('因子 ID 使用小写字母、数字和连字符');if(!/^\d+\.\d+\.\d+$/.test(definition.factor_version))errors.push('版本格式例如 1.0.0');if(!definition.start||!definition.end||definition.start>definition.end)errors.push('计算起止日期不合法');if(definition.mode==='custom'){if(!definition.hypothesis.trim())errors.push('请填写研究假设');if(!definition.formula.trim())errors.push('请填写公式');const identifiers=definition.formula.match(/[A-Za-z_][A-Za-z_0-9]*/g)||[];const allowed=[...fields,'Ref','Mean','Std','Sum','Log','Abs'];for(const id of new Set(identifiers))if(!allowed.includes(id))errors.push('字段或算子不在当前 SQL 入口支持范围：'+id);if(/[^A-Za-z0-9_\s+*/().,\-]/.test(definition.formula))errors.push('表达式包含不支持的字符');if(/(?:Ref|Mean|Std|Sum)\([^,]+,\s*-/.test(definition.formula))errors.push('窗口必须为正整数，不可读取未来数据');let depth=0;for(const c of definition.formula){if(c==='(')depth++;if(c===')')depth--;if(depth<0)break}if(depth!==0)errors.push('括号不匹配')}
 return errors;
 }
 function command(){return `python scripts/publish_factor_release.py --catalog-profile ${definition.profile==='initial'?'initial':'m4.2'} --start ${definition.start} --end ${definition.end}`}
 function computationDraft(){return {schema_version:1,status:'FRONTEND_DRAFT_NOT_SUBMITTED',definition:{...definition},source:source?{report_id:r().report_id,universe_id:r().universe_id}:null,backend_entry:definition.mode==='catalog'?'scripts/publish_factor_release.py':null,command:definition.mode==='catalog'?command():null,requires_backend:definition.mode==='custom'?['Compile expression and derive temporal dependencies / implementation hash','Register immutable FactorSpec / catalog entry','Expose computation submission API']:['Expose existing publisher as a computation API'],note:'前端配置草稿；不是已注册因子或已提交任务。目录计算会计算该 profile 的整套因子，不支持仅挑选单个公式。'}}
 function editor(){const f=(label,key,type='text')=>U.field(label,`<input data-def="${key}" aria-label="${label}" type="${type}" value="${E(definition[key])}">`);modal('因子计算配置 · 沿用现有后端流程',`<div class="notice notice-blue">已有入口为 Python 发布脚本，尚未确认计算 HTTP 接口。这里先准备可复现配置，不生成演示任务。</div><div class="form-grid" style="margin-top:16px">${U.field('计算对象',`<select data-def="mode" aria-label="计算对象"><option value="custom" ${definition.mode==='custom'?'selected':''}>新增表达式因子</option><option value="catalog" ${definition.mode==='catalog'?'selected':''}>已有目录批量计算</option></select>`)}${U.field('已有目录',`<select data-def="profile" aria-label="已有目录"><option value="m4.2" ${definition.profile==='m4.2'?'selected':''}>m4.2 · 复权公式版本</option><option value="initial" ${definition.profile==='initial'?'selected':''}>initial · 初始版本</option></select>`)}${f('因子 ID','factor_id')}${f('因子名称','name')}${f('因子版本','factor_version')}${f('因子类别','family')}${f('起始交易日','start','date')}${f('结束交易日','end','date')}${U.field('先验方向',`<select data-def="direction" aria-label="先验方向">${['POSITIVE','NEGATIVE','TRAIN_FIT'].map(x=>`<option ${x===definition.direction?'selected':''}>${x}</option>`).join('')}</select>`)}${U.field('产物变体','<input value="RAW · 原始值发布" disabled>')}</div><label class="field" style="margin-top:16px">因子表达式<textarea class="be-formula" data-def="formula" aria-label="新因子公式">${E(definition.formula)}</textarea></label><label class="field">研究假设<textarea data-def="hypothesis" aria-label="研究假设">${E(definition.hypothesis)}</textarea></label><p class="small muted">支持 Ref / Mean / Std / Sum / Log / Abs；时间序列函数首参为字段名，窗口为正整数。依赖、预热与实现哈希仍须后端编译确认。预处理发布需要 RAW release_id，不能提前编造。</p><div id="be-validation" role="status"></div><details><summary>现有计算输入字段</summary>${fields.map(E).join('、')}</details>`,btn('检查配置','validate')+btn('保存计算草稿','save-definition')+btn('导出配置 / 命令','export-compute')+'<button class="btn btn-primary" disabled title="尚未确认后端计算 HTTP 契约">一键计算 · 待接入接口</button>')}
 function recordDefinition(){try{localStorage.setItem(definitionKey,JSON.stringify(definition));State.factorDraft={name:definition.name,formula:definition.formula};return true}catch{toast('浏览器保存失败，请导出草稿');return false}}
 document.addEventListener('input',e=>{if(e.target.dataset.def)definition[e.target.dataset.def]=e.target.value;if(e.target.id==='compute-factor-name')definition.name=e.target.value;if(e.target.id==='compute-formula')definition.formula=e.target.value});
 document.addEventListener('change',e=>{if(e.target.dataset.def){definition[e.target.dataset.def]=e.target.value;document.getElementById('be-validation').textContent='配置已变更，请重新检查。'}if(e.target.dataset.factor)saveSelection()});
 document.addEventListener('click',e=>{const el=e.target.closest('[data-be],[data-action]');if(!el)return;const a=el.dataset.be,old=el.dataset.action,id=el.dataset.id;
 if(['save-factor-definition','new-compute','submit-compute'].includes(old)){e.preventDefault();e.stopImmediatePropagation();if(old==='save-factor-definition'){if(recordDefinition())toast('已保存本地定义草稿，尚未注册后端')}else editor();return}
 if(!a){if(old==='select-factor'||old==='save-feature-set')queueMicrotask(saveSelection);return}e.preventDefault();e.stopImmediatePropagation();
 if(a==='refresh')refresh();if(a==='configure')editor();if(a==='sources')modal('现有工程 · 来源与边界',source?json({source_root:source.source_root,read_at:source.read_at,report:r(),sources:source.sources,warnings:source.warnings}):'<p>尚未读取成功；使用本地预览服务打开页面。</p>');if(a==='detail')factorDetail(id);
 if(a==='rebind'){State.selectedFactors=new Set();sourceReport=r().report_id;saveSelection();invalidate('factors');render(true)}
 if(a==='template')modal('从后端已有公式建立新草稿',U.table(['因子','版本','操作'],(source?.evidence.factors||[]).filter(f=>f.variant==='RAW').map(f=>[E(f.name),E(f.factor_version),btn('载入','clone',`data-id="${E(f.entity_id)}"`)])));
 if(a==='clone'){const f=source?.evidence.factors.find(f=>f.entity_id===id);if(!f)return;definition={...definition,mode:'custom',name:f.name+' · 新版本',factor_id:f.factor_id+'-custom',factor_version:'1.0.0',formula:f.formula,family:f.family,direction:f.direction,hypothesis:f.economic_hypothesis};recordDefinition();editor()}
 if(['validate','save-definition','export-compute'].includes(a)){const errors=validate();const box=document.getElementById('be-validation');if(box)box.innerHTML=errors.length?`<div class="notice notice-amber">${errors.map(E).join('<br>')}</div>`:'<div class="notice notice-blue">基础字段检查通过；不是后端语法编译或计算成功。</div>';if(errors.length)return;if(a==='save-definition'&&recordDefinition())toast('已保存计算草稿，尚未提交');if(a==='export-compute'){recordDefinition();download('factor-compute-draft.json',JSON.stringify(computationDraft(),null,2));if(definition.mode==='catalog')modal('已有目录 · 计算命令',`<p>在 ${E(source?.source_root||'后端项目根目录')} 运行；将计算整套目录并发布 RAW 版本。前端没有执行此命令。</p><pre class="code">${E(command())}</pre>`)} }
 },true);
 // Keep the existing shell, navigation, actions and workflow wrappers.
 const oldRender=render;render=function(keep){oldRender(keep);if(State.page==='intelligence')return;const badge=document.querySelector('#topbar .badge');if(badge)badge.textContent=source?'真实产物已合并 · 保留设计样例':'原设计 · 产物连接中';const footer=document.querySelector('footer');if(footer)footer.innerHTML='研序 QUANT · 研究设计与现有工程 <span>真实数据区标明来源；其余样例与未接入执行器保留原设计</span>';const counter=document.querySelector('#sidebar .nav-count');if(counter&&source)counter.textContent=FACTORS.length;};
 async function refresh(){if(loading)return;loading=true;try{const response=await fetch('/api/research-snapshot',{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('HTTP '+response.status);const next=await response.json();if(!Array.isArray(next.evidence?.factors))throw Error('快照结构不匹配');const first=!source;source=next;loadError='';
 const categories={momentum:'动量',reversal:'动量',volatility:'波动',liquidity:'流动性',value:'估值',quality:'质量',size:'风格',technical:'量价'};
 FACTORS=source.evidence.factors.map(f=>({id:f.entity_id,name:E(f.name)+' · '+E(f.variant),category:categories[f.family]||'量价',ic:f.basic_evidence?.mean_rank_ic??null,ir:null,coverage:(f.basic_evidence?.mean_coverage??0)*100,status:'已完成',version:f.factor_version,formula:f.formula,role:'预测',direction:({POSITIVE:'正向',NEGATIVE:'反向',TRAIN_FIT:'待确定'})[f.direction]||'待确定',description:f.economic_hypothesis,backend:true}));
 if(first){let saved;try{saved=JSON.parse(localStorage.getItem(storeKey))}catch{}sourceReport=saved?.report_id||r().report_id;State.selectedFactors=new Set((saved?.entities||[]).filter(id=>FACTORS.some(f=>f.id===id)));State.selectionIds=undefined;State.selectionRan=false;}
 }catch(e){loadError=location.protocol==='file:'?'离线文件不读取后端，请访问 http://127.0.0.1:8871':'后端产物读取失败：'+e.message}
 try{const response=await fetch(qualityApiUrl,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('HTTP '+response.status);const next=await response.json();if(next.schema_version!==1||!Array.isArray(next.checks))throw Error('响应结构不匹配');quality=next;qualityError=''}catch(e){qualityError='后端质量接口刷新失败：'+e.message}
 finally{loading=false;if(overlay.hidden&&!document.activeElement?.matches('input,textarea,select'))render(true)}}
 render(true);refresh();setInterval(()=>{if(!document.hidden)refresh()},60000);
})();
