/* System blueprint and paper-monitor design. All figures are demonstration fixtures. */
(() => {
  const link = (page, label) => `<button class="btn btn-quiet" data-page="${page}">${label} →</button>`;
  const fold = (title, body, open = false) => `<details class="card" ${open ? 'open' : ''}><summary style="padding:20px 24px;cursor:pointer;font-weight:600">${title}</summary><div class="card-body">${body}</div></details>`;
  const step = (n, title, text) => `<div class="mini-step"><span class="step-circle">${n}</span><div><strong>${title}</strong><p>${text}</p></div></div>`;

  Pages.blueprint = () => {
    const U = UI;
    const chain = [['data','01','行情与资产','接入 · 校验 · 快照'],['compute','02','因子工程','计算 · 评估 · 筛选'],['dataset','03','研究数据集','股票池 · 标签 · 切分'],['training','04','模型与信号','训练 · 验证 · 注册'],['backtest','05','组合与回测','构建 · 撮合 · 归因'],['monitor','06','模拟跟踪','冻结 · 观测 · 复核']];
    const pageMap = [
      ['overview','研究工作台','资产与任务摘要','查看缺口、继续研究','研究入口','数据 / 任务','首期'],
      ['data','数据中心','现有行情、证券与历史成分','接入、预览、质量校验','不可变行情快照','因子计算','首期'],
      ['compute','因子计算','公式版本 + 行情快照','依赖检查、增量 / 补算','因子分区与任务记录','因子资产库','首期'],
      ['factors','因子资产库','已发布因子值','IC、分组、衰减、覆盖评估','因子评估版本','因子筛选','首期'],
      ['selection','因子筛选','候选因子与训练窗口','稳定性、相关去重、组合增益','有方向的特征集版本','样本与标签','首期'],
      ['dataset','样本与标签','特征集、历史股票池','标签定义、预处理、时间切分','冻结数据集与清洗报告','模型实验室','首期'],
      ['training','模型实验室','数据集与模型参数','训练、滚动验证、对比、注册','模型 + 变换器 + 预测产物','策略构建','首期'],
      ['strategy','策略构建','规则评分或模型预测','选股、权重、约束、调仓','策略配置版本','回测与归因','首期'],
      ['backtest','回测与归因','策略、数据快照、规则版本','撮合、费用、收益与偏差审计','净值 / 订单 / 成交 / 审计包','模拟跟踪','首期'],
      ['intelligence','情报研究','公告 / 新闻 / 热点 / 舆论 + 行情快照','多角色观察、产业推演、反证与文字报告','证据快照 / 报告版本 / 跟踪计划','事件研究集 / 因子验证','扩展'],
      ['monitor','模拟跟踪','锁定候选策略与每日数据','生成计划、记录模拟成交、监控漂移','每日模拟账本与告警','复核 / 新实验','后期'],
      ['tasks','任务中心','各模块异步作业','依赖调度、日志、取消、重试','任务状态与产物引用','返回发起模块','首期'],
      ['blueprint','系统蓝图','页面、对象与接口约定','查看架构与接入验收','实施范围与数据契约','分阶段实现','设计']
    ];
    return `<div class="stack">
      <div class="notice notice-blue">当前已知基础：你已有行情数据，因子正在分批计算。本页定义后续接入方式；页面中的数字和记录均为演示，尚未连接你的真实数据。</div>
      ${U.card('让每一次研究，都有一条可追溯的链路','从已有数据出发，把因子、模型和策略连接成可复现的研究系统。',`<div class="pipeline">${chain.map(x=>`<button class="pipe-node" data-page="${x[0]}"><div class="pipe-num">${x[1]}</div><div class="pipe-name">${x[2]}</div><div class="pipe-status">${x[3]}</div></button>`).join('')}</div><div class="divider"></div><div class="grid-3"><div><strong>数据是资产</strong><p class="small muted">行情、因子和历史股票池都有来源、时间范围、质量与固定版本。</p></div><div><strong>实验是过程</strong><p class="small muted">记录输入快照、特征、标签、参数、代码与运行环境，支持复现和比较。</p></div><div><strong>策略是可执行约定</strong><p class="small muted">信号转换为目标组合；回测显式处理成本、交易约束与实际成交。</p></div></div>`,U.badge('全链路设计','blue'))}
      <div class="grid-2">
      ${U.card('先接入已有成果','不需要等全部因子计算完毕',`${step('1','盘点与只读适配','确认数据位置、格式、字段、复权与单位；从现有文件、数据库或服务读取。')}${step('2','按分区登记因子','已完成的因子 × 日期分区先校验和发布；待算、失败、预热不足分别登记。')}${step('3','跑通最小研究闭环','选择已覆盖的一组因子和日期窗口，冻结样本，完成基线训练与一次回测。')}${link('data','查看接入设计')}`)}
      ${U.card('首期架构保持紧凑','一个 API 服务 + 后台 Worker + 统一资产目录',`${step('A','复用计算能力','现有行情与因子脚本包装为适配器；Qlib 可作为研究引擎，已有因子无需强制重算。')}${step('B','计算与页面解耦','页面提交配置并获得 job_id；后台异步执行，页面按任务状态获取结果。')}${step('C','存储按职责组织','现有行情存储继续保留；分区文件承载数值，关系数据库承载目录、版本、任务和审计。')}`)}
      </div>
      ${U.card('系统组成与数据流','逻辑模块划分；首期无需将每个模块拆成独立服务',`<div class="stack"><div class="notice"><strong>研究工作台</strong>&nbsp; 数据浏览 / 因子研究 / 模型实验 / 策略回测 / 任务与审计</div><div style="text-align:center" class="muted">↓ 查询资产 / 提交配置　↑ 状态 / 指标 / 产物</div><div class="grid-2"><div style="border:1px solid #dce6e1;border-radius:10px;padding:18px"><strong>业务 API · 模块化单体</strong><p class="small muted">资产目录、配置版本、实验记录、权限校验、结果查询；不在请求中运行长任务。</p></div><div style="border:1px solid #dce6e1;border-radius:10px;padding:18px"><strong>作业队列与 Worker</strong><p class="small muted">校验 → 因子计算 → 样本构建 → 训练 → 预测 → 回测；依赖状态、资源配额、重试与心跳。</p></div></div><div style="text-align:center" class="muted">↓ 读取固定版本　↑ 校验后提交产物</div><div class="grid-4">${[['原始层','原始文件 / 现有数据库','保留来源与原始修订'],['规范层','证券、交易日历、行情','单位、复权、可知时间'],['因子层','定义、分区值、覆盖','因子版本与缺失原因'],['产物层','数据集、模型、报告','清单、摘要与输入血缘']].map(x=>`<div style="border:1px solid #e3e9ed;border-radius:10px;padding:16px"><span class="badge badge-blue">${x[0]}</span><p><strong>${x[1]}</strong></p><span class="small muted">${x[2]}</span></div>`).join('')}</div><div class="notice"><strong>横向资产目录</strong>&nbsp; 元数据与版本引用 / 任务日志 / schema 与 manifest / 权限与审计 / 备份与保留策略</div><p class="small muted">建议先复用现有存储，必要时以 Parquet 分区承载因子值，以 PostgreSQL 管理并发元数据；本机原型阶段也可使用 SQLite。Qlib 格式视为可重建的引擎缓存，原始与规范数据保持独立。框架与引擎的选择属于实施方案，不代表目前已安装或接通。</p></div>`)}
      ${fold('页面地图 · 每个页面的输入、操作、产物与下一步',U.table(['页面','输入','主要操作','产物','下一步','阶段'],pageMap.map(x=>[link(x[0],x[1]),x[2],x[3],x[4],x[5],U.badge(x[6],x[6]==='后期'?'amber':'neutral')])))}
      ${blueprintContracts(U)}
      ${blueprintDelivery(U)}
    </div>`;
  };
  function blueprintContracts(U){return fold('核心对象与接入契约 · 保证整条链路可复现',`<div class="stack">${U.table(['对象','唯一标识 / 关联','必须记录的内容'],[['行情快照','snapshot_id','来源、schema、校验摘要、时间范围、可知时间'],['因子定义','factor_id + version','公式、参数、预热窗口、依赖、代码 hash'],['因子分区','factor_version + snapshot + date + instrument','数值、单位、有效状态、分区 manifest'],['特征集','feature_set_id + version','因子版本、方向、用途、筛选证据、研究窗口'],['数据集','dataset_id + version','特征集、标签、股票池、split、预处理器'],['实验 / 模型','experiment_id → model_version','数据集、代码、环境、种子、参数、验证产物'],['策略 / 回测','strategy_version → backtest_id','信号源、组合约束、撮合与费用规则版本'],['任务 / 审计','job_id / trace_id','状态、依赖、重试、日志、操作者、产物清单']])}<div class="notice notice-blue">版本引用链：market_snapshot → factor_partition → feature_set → dataset → experiment → model → strategy → backtest → paper_run。任何输入修订都生成新版本，旧报告继续引用旧版本。</div><div class="grid-2"><div><h3>双时间与真实可用范围</h3><p class="small muted">trade_date / event_time 表示数据所属时间；available_at 表示实际可知时间。研究查询同时满足业务时间与可知时间限制。财务修订保留原始披露版本，不用最新值回填历史。</p></div><div><h3>分区状态与完整性</h3><p class="small muted">planned → running → computed → validated → published；failed / canceled 单独记录。值状态区分有效、预热、停牌、源缺失、未计算。watermark 与覆盖率分开，不把局部完成当作全区间可用。</p></div></div><pre class="code">现有数据 / 计算脚本
  → 输出批次清单（文件位置、行数、schema、checksum、因子版本）
  → 暂存与字段映射（证券代码、日期、价格/成交量单位）
  → 校验唯一键、可知时间、覆盖和数值范围
  → 原子提交 manifest，发布不可变分区快照
  → 更新可用区间，按依赖解锁样本 / 训练任务
  → 源数据订正时，登记影响范围并生成新产物</pre><div class="grid-2"><div><h3>异步任务接口 · 建议</h3><pre class="code">POST /jobs        提交类型、输入版本、参数、幂等键
GET  /jobs/{id}   查询状态、分区进度、错误和产物
POST /jobs/{id}/cancel   请求停止
POST /jobs/{id}/retry    保留原记录后重试
GET  /assets/{id}/lineage  查看上下游版本</pre></div><div><h3>权限、配置与保留</h3><p class="small muted">浏览者只读资产与报告；研究员创建草稿与实验；管理员管理数据源、资源和规则。数据发布、模型注册、规则变更均保留审计记录。连接密钥留在服务端，不写入研究配置；产物备份与恢复纳入验收。</p></div></div></div>`)}
  function blueprintDelivery(U){return fold('实施路线与验收 · 先把已有行情和因子融合进来',`<div class="grid-3"><div class="small-stat"><span class="badge badge-green">P0 · 接入与闭环</span><h3 style="margin:12px 0">让已有成果可管理</h3><p class="small muted">先实现数据目录、字段映射、因子分区登记、任务日志和小范围样本。用简单等权或线性基线完成首个可复现回测。</p><div class="divider"></div><p class="small">验收：源行数与校验一致；缺失原因可查；已完成因子可独立接入；同配置可重跑。</p></div><div class="small-stat"><span class="badge badge-blue">P1 · 研究平台</span><h3 style="margin:12px 0">让研究可比较、可追溯</h3><p class="small muted">实现单因子画像、筛选证据、数据集冻结、滚动训练、模型注册、策略构建、成交回测与归因。</p><div class="divider"></div><p class="small">验收：测试集不参与筛选；所有结果绑定版本；目标与实际持仓分离；成本和拒单可核对。</p></div><div class="small-stat"><span class="badge badge-amber">P2 · 模拟与扩展</span><h3 style="margin:12px 0">让候选策略接受持续检验</h3><p class="small muted">每日信号计划、模拟账本、数据与模型漂移、策略复核；再按需要扩展分钟数据和更多模型。</p><div class="divider"></div><p class="small">验收：锁定版本连续跟踪；缺失数据可阻断；异常可回溯。真实交易接入另立项目评审。</p></div></div><div class="divider"></div><h3>与截图的关系</h3><p class="small muted">截图用作功能与信息呈现参考。截图中的因子收益、评分、税费、参数默认值和策略结论均不继承为本系统事实。本原型采用自行组织的页面、数据模型与研究流程。</p><div class="divider"></div><h3>技术依据</h3><p class="small muted">实现前应以选定版本文档复核接口。<a href="https://qlib.readthedocs.io/en/latest/component/workflow.html" target="_blank" rel="noopener">Qlib 工作流与实验管理</a> · <a href="https://qlib.readthedocs.io/en/latest/component/data.html" target="_blank" rel="noopener">Qlib 数据层</a> · <a href="https://scikit-learn.org/stable/common_pitfalls.html" target="_blank" rel="noopener">scikit-learn 数据泄漏与预处理</a> · <a href="https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html" target="_blank" rel="noopener">TimeSeriesSplit</a> · <a href="https://lightgbm.readthedocs.io/en/stable/Parameters.html" target="_blank" rel="noopener">LightGBM 参数</a>。面板数据按交易日整体分组切分，不能将股票行数直接当作时间间隔；标签区间还需独立进行边界净化。</p>`)}
  Pages.monitor=()=>{const U=UI;return `<div class="stack"><div class="notice notice-blue"><span>后续阶段 / 模拟跟踪：锁定研究版本后观察信号与执行表现。这里不连接交易账户，不产生真实订单。</span>${U.badge('P2 设计','blue')}</div><div class="grid-4">${U.metric('候选策略','STR-003','固定模型 MODEL-003')}${U.metric('模拟观察 · 演示','42 <small>天</small>','版本与参数保持不变')}${U.metric('信号覆盖 · 演示','99.2%','最新样例截面')}${U.metric('待复核 · 演示','02','覆盖下降 / 行业偏离')}</div>${U.card('每日运行链路','数据到齐与质量通过后，才允许生成当天信号',`<div class="pipeline">${['校验行情','检查因子','固定模型推理','组合约束','模拟成交','账本与告警'].map((x,i)=>`<div class="pipe-node"><div class="pipe-num">0${i+1}</div><div class="pipe-name">${x}</div><div class="pipe-status">${i===2?'固定版本':'记录证据'}</div></div>`).join('')}</div>`)}<div class="grid-2">${U.card('策略监测与复核','阈值属于研究配置，需要历史标定',U.table(['监测项','演示状态','处理'],[['数据新鲜度',U.badge('通过','green'),'按预期发布时点检查'],['特征覆盖率',U.badge('需关注','amber'),'缺少必需因子时阻断推理'],['预测分布漂移',U.badge('待复核','amber'),'分布距离与历史基线比较'],['成交偏差',U.badge('可追溯','green'),'目标、订单、成交和持仓逐层核对'],['滚动表现','标签成熟后评估','不将未成熟收益标签用于诊断']]),U.button('设置预警规则','monitor-alerts','quiet'))}${U.card('目标与模拟持仓','示例证券，不代表推荐',U.table(['标的','目标权重','模拟权重','偏差原因'],[['DEMO001','3.33%','3.25%','数量约束与剩余现金'],['DEMO002','3.33%','0.00%','涨停未成交'],['DEMO003','0.00%','2.90%','停牌无法卖出'],['现金','5.00%','8.51%','成交受限保留现金']]),U.button('查看模拟信号','monitor-signals','quiet'))}</div>${U.card('版本冻结与退出机制','在模拟阶段验证真实运行条件，不自动回头优化历史结果',`<div class="grid-3">${step('1','冻结运行包','保存模型、预处理、特征集、股票池、规则与资金配置。更新任何核心输入时创建新候选版本。')}${step('2','异常暂停','缺少必需数据或 schema 不兼容时停止新信号。持仓与现金账本继续保留，错误须有处理记录。')}${step('3','触发复核','持续漂移、收益衰减或成交偏差触发人工复核；建立新实验后重新验证，不静默替换在线模型。')}</div>`)} </div>`};
  window.handleExtraAction=(a)=>{if(a==='monitor-alerts'){modal('模拟预警规则 · 设计配置',`<div class="form-grid">${UI.field('最低特征覆盖率（%）',UI.input('alert-coverage',State.alertCoverage||98,'number'))}${UI.field('连续异常天数',UI.input('alert-days',State.alertDays||3,'number'))}</div><p class="small muted" style="margin-top:16px">当前只保存本地会话配置。正式预警需给出指标口径、参考窗口、阈值来源和触发证据。</p>`,UI.button('保存本地规则','save-alerts','primary'));return true}if(a==='save-alerts'){const c=Number(document.getElementById('alert-coverage').value),d=Number(document.getElementById('alert-days').value);if(c<0||c>100||d<1||!Number.isInteger(d)){toast('请填写 0—100 的覆盖率和正整数天数');return true}State.alertCoverage=c;State.alertDays=d;closeModal();toast('模拟预警规则已保存到本次会话');return true}if(a==='monitor-signals'){modal('模拟信号计划 · 示例',UI.table(['日期','策略版本','信号','执行时点'],[['2026-09-04','STR-003','生成目标组合','下一交易日开盘'],['2026-09-04','MODEL-003','score 版本固定','仅模拟执行']])+`<p class="small muted" style="margin-top:16px">正式页面保存逐证券原始分数、过滤原因、目标权重与最终模拟成交记录。</p>`,UI.button('关闭','close-modal'));return true}return false};
})();
